install.packages("formattable")
install.packages("DiagrammeR")
install.packages("data.tree")
install.packages("remotes")
remotes::install_github("gluc/ahp")
library(ahp)
library(data.tree)
library(formattable)
library(DiagrammeR)
ahpFile <- "C:/Users/danie/OneDrive/Pulpit/Apu/lab2.ahp"
smAhp <- Load(ahpFile)
print(smAhp, filterFun = isNotLeaf)
Calculate(smAhp)
print(smAhp, "cena")
print(smAhp)